### ISSUE TITLE
README code isn't runnable

### ISSUE THREAD

**Issue by lorr1** [hyparam/hyparquet#1]
Copy pasted code from the readme
```
import { parquetMetadata } from 'hyparquet'

const metadata = parquetMetdata(arrayBuffer)
```

How do I load an arrayBuffer?

**Comment by platypii** [comment]
Oh sorry I thought it would be clear to an experienced javascript developer.

Are you using it in the browser or in a node.js environment?

**Comment by platypii** [comment]
Updated the README in https://github.com/hyparam/hyparquet/commit/58aed8d9cd871edb55b7344031096bbc2f9be763. Hope that solves your problem @lorr1

**Comment by lorr1** [comment]
I'm a firm believe in speedback. Thanks!
