### ISSUE TITLE
compressor option missing for parquetMetadataAsync

### ISSUE THREAD

**Issue by Sirach99** [hyparam/hyparquet#15]
Is there a way to call `parquetMetadataAsync` for GZIP codecs? 
It seems the option to pass compressors from `hyparquet-compressors` is missing.

**Comment by platypii** [comment]
The metadata is not compressed, so there should be no need to pass a compressors object if you just want the metadata.

**Comment by Sirach99** [comment]
Thanks @platypii!

Maybe I'm doing something but how can I call `parquetMetadataAsync` for GZIP compressed parquet file? I am getting [this error thrown](https://github.com/hyparam/hyparquet/blob/543eba0307900befff2e594239e61f1b8c759316/src/metadata.js#L44).

When the file is compressed with Snappy, I am able to successfully use `parquetMetadataAsync`.

**Comment by Sirach99** [comment]
@platypii any update here?

**Comment by platypii** [comment]
I can't really help much without an example parquet file. I assure you that the metadata is not compressed, so there should be no difference in gzip vs snappy files on the metadata. If you're getting that error, it's either an invalid parquet file, or you are not passing in a buffer with the full file data?

Can you either share an example parquet file, or drop your file here and see if the same thing happens?
https://hyparam.github.io/hyparquet/

**Comment by Sirach99** [comment]
Thank you @platypii  Might be another issue then.
I get the same error on https://hyparam.github.io/hyparquet/ , the error is being thrown from [here]
(https://github.com/hyparam/hyparquet/blob/3ea58cb0b907a0834e9ae1a24c96d9ad7d74bb08/demo/demo.js#L93). 

Here's the parquet file from which I create a link before dragging / dropping. 
[test_file.parquet.zip](https://github.com/user-attachments/files/16072619/test_file.parquet.zip)

**Comment by platypii** [comment]
It looks like you're trying to open a zipped parquet file, which is different than the parquet file itself. See screen share:

https://github.com/hyparam/hyparquet/assets/1766297/5256b946-b05f-47ba-876d-590726e3e9b5

**Comment by Sirach99** [comment]
Ah, I forgot to mention I zipped the file because GitHub doesn't allow `.parquet` uploads. 
Albeit, during testing I had not zipped the file.

Also, here's code that shows exactly what I meant by the GZIP / Snappy difference I'm seeing

```
import { parquetMetadataAsync } from 'hyparquet';
import * as fs from 'fs';

class Foo{

    async foo(filepath){
        let file = await this.createFileConfiguration(filepath);
        let metadata = await parquetMetadataAsync(file); // this errors
        return metadata;
    }

    async createFileConfiguration(filepath) {
        let fileStats = await fs.promises.stat(filepath);
        //asyncBuffer
        return {
            byteLength: fileStats.size,
            slice: async (start, end) => {
                let parquetStream = fs.createReadStream(filepath, {start, end});
                return this.readStreamToArrayBuffer(parquetStream);
            },
        };
    }

    readStreamToArrayBuffer(stream) {
        return new Promise((resolve, reject) => {
            let chunks = [];
            stream.on('data', chunk => chunks.push(chunk));
            stream.on('end', () => resolve(Buffer.concat(chunks).buffer));
            stream.on('error', reject);
        });
    }
    
}

new Foo().foo('*Insert file* - GZIP Parquet file fails, Snappy parquet file succeeds')
    .then((metadata) => console.log('metadata: ', metadata))
    .catch((error) => console.log(error));
```

@platypii

**Comment by platypii** [comment]
Ah okay I found the problem. There was a bug in `readStreamToArrayBuffer` which was defined in `benchmark.js`. The problem was that it wasn't properly slicing the returned ArrayBuffer, so it was returning an over-sized ArrayBuffer with length 8092 instead of 1249. I don't think it had anything to do with gzip vs snappy, just the file size. If you make the following change your example should work:

```js
    input.on('end', () => {
      const buffer = Buffer.concat(chunks)
      resolve(buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength))
    })
```

See commit https://github.com/hyparam/hyparquet/commit/1885c96c

Thanks @Sirach99 for raising this issue and sticking with it!

**Comment by Sirach99** [comment]
Awesome! Thank you very much for your help looking into that @platypii
