### ISSUE TITLE
Async reads: onComplete returns column data in unpredictable order

### ISSUE THREAD

**Issue by andynsd** [hyparam/hyparquet#19]
Hi folks, this is an awesome library. It is simple and powerful. Nice job!

I was running into an issue when asynchronously reading larger parquet files where the `onComplete` handler was giving me back column data in a different order each time. I couldn't figure out a way to determine what order the columns were in. I think part of the problem is that my `slice` function is highly async and not guaranteed to come back in any particular order.

I looked through the code and didn't see anything that would guarantee the order of the async slice calls. One potential solution is that the column data be resolved via promise rather than pushed onto an array, for example on this line: https://github.com/hyparam/hyparquet/blob/master/src/read.js#L189

Something like this could be used: `const groupColumnData = await Promise.all(promises)`

In the meantime I was able to find the `onChunk` callback which does not seem to be well-documented. I was able to workaround the issue by collecting the chunks manually because they are emitted alongside the column name.

Has anyone encountered this issue before? Maybe I'm missing something.

**Comment by m-mohr** [comment]
I think I have the same issue. The array that I receive is not in the order of the columns that I read from the metadata.

**Comment by platypii** [comment]
Thanks @andynsd and @m-mohr I was able to re-pro this bug, and have just pushed a fix in #21. Will publish a new version of the library shortly.
