### ISSUE TITLE
After read parquet file  by parquetRead  result object is not full

### ISSUE THREAD

**Issue by menesty** [hyparam/hyparquet#23]
Hi, 
version : ^1.1.0
I have file parquet compression SNAPPY, when 
```
let fileData: any[][] = [];

	var asyncBuffer: AsyncBuffer = await asyncBufferFromUrl(url);
	await parquetRead({
		file: asyncBuffer,
		compressors: {
			SNAPPY: snappyUncompressor()
		},
		onComplete: (data): void => {
			fileData = data;
		}
	});
```
parsed result is not complete
[22425501.parquet.zip](https://github.com/user-attachments/files/16425046/22425501.parquet.zip)
in unparsed structure missed Menu->categories->dishes->addons->items-> price, volume, ingredient (this object total unparsed) in source data for this object is present 
from source file
`���Dish extra 1���Dodatki do ≈õniadania�  ƒ•∆Ö����������Ì���<��ˇˇˇˇ�""ÎÂÄˆ���������Ì����òòÖ®ÿ������‡»����∂Ì���21985972���21985948���22861716���22673128���22672907XX≤£ﬂº
<�����861005���20997760���11742617���895653�((ùÒôÊ�����‡»����ˇˇ‰�$$øÙª€<�����UK���EN���PL�88Ω≠â¿
�����h9∂l�������§í$�  ùÄËÙ<�����–¶–µ–±—É–ª—è���Onion���Cebula���asd
���≈ömietana 12%���–ö–∞—Ä—Ç–æ–ø–ª—è���Potato���Ziemnaik�<<‹®à¯�����h9∂l�������à∆˙à��`
In parsed 
ingredient: undefined In source value for this field is preset (it required field)
price: undefined, (some is filled some empty but in parsed i missed for all)
volume: undefined (some is filled some empty but in parsed i missed for all)

**Comment by platypii** [comment]
@menesty thanks for the report and the clear repro steps.

I've just published a new version v1.1.1 which includes a fix for nested struct parsing. The output now matches pyarrow and duckdb. Please let me know if that solves your problem!
