### ISSUE TITLE
Facing issue - Error: parquet unsupported page type: undefined

### ISSUE THREAD

**Issue by vivien-ks** [hyparam/hyparquet#30]
Hi, I'm facing an error where it mentions that there is a page that is undefined. according to the logs, it happens at readColumn. Can I check how I can bypass this error? 

`await hyparquet.parquetRead({
                file: response.buffer,
                rowFormat: 'object',
                onComplete: (data: any) => {
                    console.log(data);
                }
            });`

My response is in Uint8Array. 

Thank you!

**Comment by platypii** [comment]
I haven't seen that error before. Can you provide a parquet file that reproduces the issue? If you can't provide the specific file, it would be helpful if you could share the parquet metadata (can be retrieved using `parquetMetadata` function, or from the viewer dropdown Table > Metadata [here](https://hyparam.github.io/hyparquet/).

**Comment by vivien-ks** [comment]
Hi, this is the parquet metadata that I obtained with the method that you have mentioned: 

`
{
  version: 1,
  schema: [
    {
      type: undefined,
      type_length: undefined,
      repetition_type: undefined,
      name: 'spark_schema',
      num_children: 2,
      converted_type: undefined,
      scale: undefined,
      precision: undefined,
      field_id: undefined,
      logical_type: undefined
    },
    {
      type: 'INT32',
      type_length: undefined,
      repetition_type: 'OPTIONAL',
      name: 'B_res',
      num_children: undefined,
      converted_type: undefined,
      scale: undefined,
      precision: undefined,
      field_id: undefined,
      logical_type: undefined
    },
    {
      type: 'INT32',
      type_length: undefined,
      repetition_type: 'OPTIONAL',
      name: 'E_res',
      num_children: undefined,
      converted_type: undefined,
      scale: undefined,
      precision: undefined,
      field_id: undefined,
      logical_type: undefined
    }
  ],
  num_rows: 155519n,
  row_groups: [
    {
      columns: [Array],
      total_byte_size: 335100n,
      num_rows: 155519n,
      sorting_columns: undefined,
      file_offset: 4n,
      total_compressed_size: 335100n,
      ordinal: 0
    }
  ],
  key_value_metadata: [
    { key: 'org.apache.spark.version', value: '3.4.2' },
    {
      key: 'org.apache.spark.sql.parquet.row.metadata',
      value: '{"type":"struct","fields":[{"name":"B_res","type":"integer","nullable":true,"metadata":{}},{"name":"E_res","type":"integer","nullable":true,"metadata":{}}]}'
    }
  ],
  created_by: 'parquet-mr version 1.12.3 (build f8dced182c4c1fbdec6ccb3185537b5a01e6ed6b)',
  metadata_length: 596
}
`

**Comment by platypii** [comment]
Thanks for the info, but I'm not sure I can fix the problem without an example parquet file. Is there any way you can share your parquet file? I can almost certainly fix it if you can provide an example file.

If you cannot provide the data, here's some of the things I would do:
 - Does the file open in other parquet readers like duckdb or pandas?
 - Does the error happen on one column or both? Try adding `columns: ["B_res"]` or `columns: ["E_res"]` to your `parquetRead` call.
 - Can you open other parquet files with hyparquet? There could be an issue with how you are reading the arraybuffer, and opening a different parquet file that is known to work would help debug that (any parquet file in this repo).

**Comment by vivien-ks** [comment]
Hi, thanks for providing some areas which I can start on debug. Let me try to download a copy of the parquet file. Meanwhile, I have tried to extract on one column as you have suggested, but I am faced with another error: 

RangeError: Invalid typed array length: 40000
    at new Uint8Array (<anonymous>)
    at readColumn (...\hyparquet\src\column.js:44:29)

**Comment by vivien-ks** [comment]
[results.zip](https://github.com/user-attachments/files/17072197/results.zip)

Hi, this is the extracted parquet file.

Thank you!

**Comment by platypii** [comment]
I am not able to open that parquet file in either `duckdb` nor `pandas.read_parquet` nor `hyparquet`. It appears that is a corrupted or invalid parquet file. Are you able to open it in anything else? Where is the file from?

**Comment by vivien-ks** [comment]
Hi, the file is actually obtained from an API. It would seem that the issue would be resolved if I coalesce my data.
Sorry for the inconvenience and thank you for the assistance!
