### ISSUE TITLE
Demo throws exception on dropped files

### ISSUE THREAD

**Issue by ngbrown** [hyparam/hyparquet#32]
When I drop a parquet file, including the sample [`rowgroups.parquet`](https://raw.githubusercontent.com/hyparam/hyparquet/master/test/files/rowgroups.parquet) onto the [demo](https://hyparam.github.io/hyparquet/), I get the following error when navigating back to the table from metadata:

> TypeError: slice method called on incompatible undefined
    slice https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1
    _e https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1
    et https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1
    et https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1
    et https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1
    tt https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1
    onmessage https://hyparam.github.io/hyparquet/demo/workers/worker.min.js:1

I was getting this error on my own dropped file that was just longer than screen length when I scrolled down.

Happens on both Chrome and Firefox.

**Comment by platypii** [comment]
@ngbrown good catch! I just pushed https://github.com/hyparam/hyparquet/commit/39f8c184a442528e5841b1a3f3407aa7fe04d4c1 let me know if that fixes it for you. Thanks!

**Comment by ngbrown** [comment]
It's working for me. Thanks.
