### ISSUE TITLE
[package] expose as a commonjs module?

### ISSUE THREAD

**Issue by severo** [hyparam/hyparquet#35]
https://arethetypeswrong.github.io/?p=hyparquet%401.5.0 reports an issue:

> [ESM (dynamic import only)](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/CJSResolvesToESM.md)
> 
> A require call resolved to an ESM JavaScript file, which is an error in Node and some bundlers. CommonJS consumers will need to use a dynamic import.

Two options:
- add a build step to publish a cjs version of the package
- assume it's ESM-only (as mentioned in https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/CJSResolvesToESM.md#common-causes), and claim it a bit more prominently in the README (here, for example: https://github.com/hyparam/hyparquet?tab=readme-ov-file#nodejs <- we show a dynamic import, we could add a sentence to say it's ESM-only and cannot be imported with `require`)

**Comment by severo** [comment]
We could also add https://github.com/marketplace/actions/are-the-types-wrong-checker as a github action, here and in the other repos, to check the package

**Comment by severo** [comment]
Note also https://github.com/isaacs/tshy, which aims to help package publishers get the package.json right when the code is typescript. It's used now by Hugging Face at https://github.com/huggingface/huggingface.js/pull/1029

**Comment by platypii** [comment]
README is updated to emphasize that it is ESM only. I think that is sufficient, the future is ESM. If someone really needs commonjs they can transpile it or use a transpiling CDN.
