### ISSUE TITLE
generate the types automatically

### ISSUE THREAD

**Issue by severo** [hyparam/hyparquet#43]
We currently have two definitions for the types. For example, asyncBufferFromUrl is not synchronized between the implementation and the type declaration (after #34):

https://github.com/hyparam/hyparquet/blob/c85d38eed53fa0a0547d35513d345cdb73ca58c3/src/utils.js#L56-L66

https://github.com/hyparam/hyparquet/blob/c85d38eed53fa0a0547d35513d345cdb73ca58c3/src/hyparquet.d.ts#L117-L121

**Comment by platypii** [comment]
Can you generate .d.ts files from jsdoc comments? Seems like it's possible with `"emitDeclarationOnly": true`. We should be careful that it's not somehow mangling the types in the process, but otherwise I agree -- would rather not have to maintain parallel type definitions that can go out of sync.

**Comment by severo** [comment]
Yes, I think it should work!

**Comment by severo** [comment]
I'm wondering: we might switch to typescript instead of using only jsdoc. If we include a build step, it might make things easier, no?

**Comment by platypii** [comment]
No. Then you need to publish map files and such. I would rather leave it as close to no-build as possible.

I wish it wasn't necessary, but adding a build step for .d.ts files I think is an okay compromise. But let's keep the code in JS.
