### ISSUE TITLE
Type definition for parquetRead options is missing utf8.

### ISSUE THREAD

**Issue by ngbrown** [hyparam/hyparquet#50]
I upgraded from v1.5.0 to v1.6.2 and am now getting a type error about the `utf8` option:

```ts
      await parquetRead({
        file: arrayBuffer,
        utf8: true,
        metadata,
        // etc...
      });
```

> error TS2353: Object literal may only specify known properties, and 'utf8' does not exist in type '{ file: AsyncBuffer; metadata?: FileMetaData | undefined; columns?: string[] | undefined; rowFormat?: string | undefined; rowStart?: number | undefined; rowEnd?: number | undefined; onChunk?: ((chunk: ColumnData) => void) | undefined; onComplete?: ((rows: any[][]) => void) | undefined; compressors?: Compressors | un...'.
> 
> 58         utf8: true,
>           ~~~~

~In the npm package, it appears that `parquetRead()` is now defined twice. Once in `src/types.d.ts` and again in `types/read.d.ts`. Typescript is only using the `types/read.d.ts` generated type file.~

The `ParquetReadOptions` options isn't used in `types/read.d.ts` and the comment definition that drives the generated `src/types.d.ts` in the npm package isn't as complete.

**Comment by platypii** [comment]
Confirmed locally that this is fixed in version 1.6.4 that was just published.

Thanks @ngbrown for raising this issue!
